name: Pull core files

on:
  workflow_dispatch:

env:
  DIRTY: FALSE

jobs:
  core-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: test
        run: |
          git branch -a
          git remote add -f -t develop --no-tags core https://github.com/kloostermanw/repo-core.git
          git remote
          git fetch
          git rm -rf src/app/Core/*
          git read-tree --prefix=src/app/Core/Models/ -u core/develop:src/includes/App/Models

      - name: Create commits
        run: |
          git config user.name 'Wiebe Kloosterman'
          git config user.email 'wiebe@celerypayroll.com'
          git add -A
          if output=$(git status --porcelain) && [ -z "$output" ]; then export DIRTY=FALSE; else export DIRTY=TRUE; fi

      - name: Commit
        if: contains(env.DIRTY, TRUE)
        run: |
          git commit -m "refactor: Update Core files."

      - name: Create Pull Request
        if: contains(env.DIRTY, 'TRUE')
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Updated core files from repo-core'
